server:
  port: 9002

spring:
  application:
    name: payment-service

  # cloud properties
  cloud:
    stream:
      function:
        definition: paymentProcessor
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event

  # datasource properties
  datasource:
    url: jdbc:h2:file:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # jpa properties
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  # h2 properties
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true