services:

  postgres:
    image: postgres:alpine3.18
    container_name: pg-db-saga
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - posgresql-2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pg-db-saga
    networks:
      - sb-postgres-network-2

  pgadmin4:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin4-saga
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgres
    networks:
      - sb-postgres-network-2

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pg-db-saga
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: pass
#    depends_on:
#      - postgres
#    networks:
#      - sb-postgres-network

volumes:
  posgresql-2:

networks:
  sb-postgres-network-2:
    driver: bridge