server:
  port: 9001

spring:
  application:
    name: order-service

  # cloud properties
  cloud:
    function:
      definition: orderSupplier;paymentEventConsumer;inventoryEventConsumer
    stream:
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event
        inventoryEventConsumer-in-0:
          destination: inventory-event

  # datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pg-db-saga
    username: postgres
    password: pass

  # jpa properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # h2 properties
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true