server:
  port: 9003

spring:
  application:
    name: inventory-service

  # cloud properties
  cloud:
    function:
      definition: inventoryProcessor
    stream:
      bindings:
        inventoryProcessor-in-0:
          destination: order-event
        inventoryProcessor-out-0:
          destination: inventory-event

  # datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pg-db-saga
    username: postgres
    password: pass

  # jpa properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  # h2 properties
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true